
### TRAER TODOS LOS PRODCUTOS
GET http://localhost:8090/product

### REGISTRAR UN PRODUCTO
POST http://localhost:8090/product
Content-Type: application/json

{
  "name": "cafe sapolio",
  "gainAmount": 5.50,
  "stock": 1,
  "reorderLevel": 10,
  "barCode": "1234161891011",
  "saleMode": "Unidad",
  "category": "Café/Infusiones"
}

### TRAER TODAS LAS CATEGORIAS 
GET http://localhost:8090/product/categories

### TRAER TODOS LOS MODOS DE VENTA
GET http://localhost:8090/product/saleModes 

### BUSCAR POR NOMBRE
GET http://localhost:8090/product/search?name=SCaafe

### BUSCAR POR CODIGO DE BARRAS
GET http://localhost:8090/product/search?barCode=1214567891123

### ACTUALIZAR PRODUCTO
PUT http://localhost:8090/product/
Content-Type: application/json

{
  "name": "cafe",
  "gainAmount": 20,
  "reorderLevel": 10,
  "saleMode": "Unidad",
  "category": "Lácteos"
}
