
### TRAER TODOS LOS PRODCUTOS
GET http://localhost:8090/product

### REGISTRAR UN PRODUCTO
POST http://localhost:8090/product
Content-Type: application/json

{
  "name": "cafeton",
  "gainAmount": 5.50,
  "stock": 1,
  "reorderLevel": 10,
  "saleMode": "Unidad",
  "category": "Café/Infusiones"
}

### TRAER TODAS LAS CATEGORIAS 
GET http://localhost:8090/product/categories

### TRAER TODOS LOS MODOS DE VENTA
GET http://localhost:8090/product/sale-modes 

### BUSCAR POR NOMBRE
GET http://localhost:8090/product/by-name?name=cafeton

### BUSCAR POR CODIGO DE BARRAS
GET http://localhost:8090/product/by-barcode?barCode=1234167891011

### ACTUALIZAR PRODUCTO
PUT http://localhost:8090/product?name=cafeton158
Content-Type: application/json

{
  "name": "Cafeton   grande  ",
  "gainAmount": 20,
  "reorderLevel": 10,
  "saleMode": "Unidad",
  "category": "Lácteos"
}
