
### TRAER TODOS LOS PRODCUTOS
GET http://localhost:8090/products

### REGISTRAR UN PRODUCTO
POST http://localhost:8090/products
Content-Type: application/json

{
  "name": "cafeton",
  "gainAmount": 5.50,
  "stock": 1,
  "reorderLevel": 10,
  "saleMode": "Unidad",
  "category": "Café/Infusiones"
}

### TRAER TODAS LAS CATEGORIAS 
GET http://localhost:8090/products/categories

### TRAER TODOS LOS MODOS DE VENTA
GET http://localhost:8090/products/sale-modes 

### BUSCAR POR NOMBRE
GET http://localhost:8090/products/by-name?name=cafeton

### BUSCAR POR CODIGO DE BARRAS
GET http://localhost:8090/products/by-barcode?barCode=1234167891011

### ACTUALIZAR PRODUCTO
PUT http://localhost:8090/products?name=cafeton158
Content-Type: application/json

{
  "name": "Cafeton   grande  ",
  "gainAmount": 20,
  "reorderLevel": 10,
  "saleMode": "Unidad",
  "category": "Lácteos"
}


### TRAER TODOS LOS PROVEEDORES
GET http://localhost:8090/suppliers

### REGISTRAR UN PROVEEDOR
POST http://localhost:8090/suppliers
Content-Type: application/json

{
  "name": "Proveedor 3",
  "phone": "147258369",
  "ruc": "12345688910"
}

### ACTUALIZAR UN PROVEEDOR
PATCH http://localhost:8090/suppliers?name=Proveedor 1 Editado
Content-Type: application/json

{
  "name": "Proveedor 1 Editado.2",
  "phone": "198765432"
}

### TRAER PROVEEDOR POR NOMBRE
GET http://localhost:8090/suppliers/by-name?name=Proveedor
